---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: prometheus
namespace: prometheus
labels:
  - pairs:
      app: prometheus
configMapGenerator:
- name: prometheus-config
  options:
    disableNameSuffixHash: true
  files:
    - config/prometheus.yaml
resources:
- namespace.yaml
- sa.yaml
- statefulset.yaml
- service.yaml
- ingress.yaml
- rbac.yaml
