---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kube-state-metrics
namespace: kube-state-metrics
labels:
  - pairs:
      app: kube-state-metrics
resources:
- namespace.yaml
- deployment.yaml
- sa.yaml
- rbac.yaml
