---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dawg-controller
  labels:
    app.kubernetes.io/name: dawg-controller
    app.kubernetes.io/component: controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dawg-controller
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: controller
      labels:
        app.kubernetes.io/name: dawg-controller
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - image: ko://github.com/jlevesy/dawg/cmd/controller
        name: controller
        env:
        - name: GRAFANA_URL
          value: http://grafana.grafana.svc.cluster.local
        - name: GRAFANA_TOKEN
          valueFrom:
            secretKeyRef:
              key: .grafanatoken
              name: grafana-token
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: dawg-controller
      terminationGracePeriodSeconds: 10
