---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: grafana
namespace: grafana
labels:
  - pairs:
      app: grafana
configMapGenerator:
- name: grafana-config
  options:
    disableNameSuffixHash: true
  files:
    - config/grafana.ini
- name: grafana-datasources
  options:
    disableNameSuffixHash: true
  files:
    - config/datasources.yaml
resources:
- namespace.yaml
- deployment.yaml
- pv.yaml
- service.yaml
- ingress.yaml
