name: ci
on:
  push:
    tags:
      - v*
  pull_request:

jobs:
  tests:
    name: Codegen And Unit Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
          check-latest: true
      - uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: '0.30.0'
      - name: Run Tests
        run: make test

  lint-code:
    name: Lint code
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
          check-latest: true
      - name: Run Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55
          args: --timeout 5m --verbose

  release:
    name: Release
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - tests
      - lint-code
    steps:
      - name: Release a New Version
        run: echo "do this when there's something to release!"
